//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRockies_one.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DugoutPitcher
    {
        public long PlayerId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<long> mlbam { get; set; }
        public string W { get; set; }
        public string L { get; set; }
        public string IP { get; set; }
        public string ERA { get; set; }
        public string H { get; set; }
        public string HR { get; set; }
        public string BB { get; set; }
        public string SO { get; set; }
        public string SB { get; set; }
        public string CS { get; set; }
        public string FB_Velo { get; set; }
        public string CutFB_Velo { get; set; }
        public string SL_Velo { get; set; }
        public string CB_Velo { get; set; }
        public string CH_Velo { get; set; }
        public string SPL_Velo { get; set; }
        public string Pitch1_Type { get; set; }
        public string Pitch2_Type { get; set; }
        public string Pitch3_Type { get; set; }
        public string Pitch4_Type { get; set; }
        public string RISP_0_0_Pitch1 { get; set; }
        public string RISP_0_0_Pitch2 { get; set; }
        public string RISP_0_0_Pitch3 { get; set; }
        public string RISP_0_0_Pitch4 { get; set; }
        public string RISP_PitAhd_Pitch1 { get; set; }
        public string RISP_PitAhd_Pitch2 { get; set; }
        public string RISP_PitAhd_Pitch3 { get; set; }
        public string RISP_PitAhd_Pitch4 { get; set; }
        public string RISP_PitBhd_Pitch1 { get; set; }
        public string RISP_PitBhd_Pitch2 { get; set; }
        public string RISP_PitBhd_Pitch3 { get; set; }
        public string RISP_PitBhd_Pitch4 { get; set; }
        public string RISP_2K_Pitch1 { get; set; }
        public string RISP_2K_Pitch2 { get; set; }
        public string RISP_2K_Pitch3 { get; set; }
        public string RISP_2K_Pitch4 { get; set; }
        public string RISP_FullCount_Pitch1 { get; set; }
        public string RISP_FullCount_Pitch2 { get; set; }
        public string RISP_FullCount_Pitch3 { get; set; }
        public string RISP_FullCount_Pitch4 { get; set; }
        public string BasesEmpty_0_0_Pitch1 { get; set; }
        public string BasesEmpty_0_0_Pitch2 { get; set; }
        public string BasesEmpty_0_0_Pitch3 { get; set; }
        public string BasesEmpty_0_0_Pitch4 { get; set; }
        public string BasesEmpty_PitAhd_Pitch1 { get; set; }
        public string BasesEmpty_PitAhd_Pitch2 { get; set; }
        public string BasesEmpty_PitAhd_Pitch3 { get; set; }
        public string BasesEmpty_PitAhd_Pitch4 { get; set; }
        public string BasesEmpty_PitBhd_Pitch1 { get; set; }
        public string BasesEmpty_PitBhd_Pitch2 { get; set; }
        public string BasesEmpty_PitBhd_Pitch3 { get; set; }
        public string BasesEmpty_PitBhd_Pitch4 { get; set; }
        public string BasesEmpty_2K_Pitch1 { get; set; }
        public string BasesEmpty_2K_Pitch2 { get; set; }
        public string BasesEmpty_2K_Pitch3 { get; set; }
        public string BasesEmpty_2K_Pitch4 { get; set; }
        public string BasesEmpty_FullCount_Pitch1 { get; set; }
        public string BasesEmpty_FullCount_Pitch2 { get; set; }
        public string BasesEmpty_FullCount_Pitch3 { get; set; }
        public string BasesEmpty_FullCount_Pitch4 { get; set; }
    }
}
