//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRockies_one.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HitterProfile_UserEntered
    {
        public long PlayerId { get; set; }
        public string Arm { get; set; }
        public string Accuracy { get; set; }
        public string Speed { get; set; }
        public string Steal { get; set; }
        public string Push { get; set; }
        public string Drag { get; set; }
        public string RHP_HowtoPitch { get; set; }
        public string LHP_HowtoPitch { get; set; }
        public string RHP_2Ks_Chase { get; set; }
        public string LHP_2Ks_Chase { get; set; }
        public string RHP_Def_INF { get; set; }
        public string LHP_Def_INF { get; set; }
        public string RHP_Def_OF { get; set; }
        public string LHP_Def_OF { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Arm_Avg { get; set; }
        public Nullable<int> Accuracy_Avg { get; set; }
        public Nullable<int> Speed_Avg { get; set; }
    }
}
