//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRockies_one.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HitterProfile
    {
        public long PlayerId { get; set; }
        public Nullable<long> MLBAM { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string AVG__vsLHP { get; set; }
        public string SLG__vsLHP { get; set; }
        public string AB_vsLHP { get; set; }
        public string H_vsLHP { get; set; }
        public string HR_vsLHP { get; set; }
        public string BB_vsLHP { get; set; }
        public string K_vsLHP { get; set; }
        public string SB_vsLHP { get; set; }
        public string CS_vsLHP { get; set; }
        public string PperPA_vsLHP { get; set; }
        public string AVG__vsRHP { get; set; }
        public string SLG__vsRHP { get; set; }
        public string AB_vsRHP { get; set; }
        public string H_vsRHP { get; set; }
        public string HR_vsRHP { get; set; }
        public string BB_vsRHP { get; set; }
        public string K_vsRHP { get; set; }
        public string SB_vsRHP { get; set; }
        public string CS_vsRHP { get; set; }
        public string PperPA_vsRHP { get; set; }
        public string AVG__Total { get; set; }
        public string SLG__Total { get; set; }
        public string AB_Total { get; set; }
        public string H_Total { get; set; }
        public string HR_Total { get; set; }
        public string BB_Total { get; set; }
        public string K_Total { get; set; }
        public string SB_Total { get; set; }
        public string CS_Total { get; set; }
        public string PperPA_Total { get; set; }
        public string GB__vsLHP { get; set; }
        public string FB__vsLHP { get; set; }
        public string GB__vsRHP { get; set; }
        public string FB__vsRHP { get; set; }
        public string GB__Total { get; set; }
        public string FB__Total { get; set; }
    }
}
