//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRockies_one.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class InsideEdEntities : DbContext
    {
        public InsideEdEntities()
            : base("name=InsideEdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<player_table> player_tables { get; set; }
        public DbSet<Team_table> Team_tables { get; set; }
    
        public virtual ObjectResult<string> sproc_depthchart_bench(Nullable<int> tID)
        {
            var tIDParameter = tID.HasValue ?
                new ObjectParameter("TID", tID) :
                new ObjectParameter("TID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sproc_depthchart_bench", tIDParameter);
        }
    
        public virtual ObjectResult<string> sproc_depthchart_disabledlist(Nullable<long> tID)
        {
            var tIDParameter = tID.HasValue ?
                new ObjectParameter("TID", tID) :
                new ObjectParameter("TID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sproc_depthchart_disabledlist", tIDParameter);
        }
    
        public virtual ObjectResult<string> sproc_depthchart_startinglineup(Nullable<int> tID)
        {
            var tIDParameter = tID.HasValue ?
                new ObjectParameter("TID", tID) :
                new ObjectParameter("TID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sproc_depthchart_startinglineup", tIDParameter);
        }
    
        public virtual ObjectResult<sproc_depthchart_startingrotation_Result> sproc_depthchart_startingrotation(Nullable<int> tID)
        {
            var tIDParameter = tID.HasValue ?
                new ObjectParameter("TID", tID) :
                new ObjectParameter("TID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_depthchart_startingrotation_Result>("sproc_depthchart_startingrotation", tIDParameter);
        }
    
        public virtual ObjectResult<sproc_playerinfo_Result> sproc_playerinfo(Nullable<long> pID)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("PID", pID) :
                new ObjectParameter("PID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_playerinfo_Result>("sproc_playerinfo", pIDParameter);
        }
    }
}
