//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRockies_one.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outfielder_Pitcher
    {
        public long PlayerID { get; set; }
        public string Aggressiveness { get; set; }
        public string SPAofHit_Summary { get; set; }
        public string SPAofHit_Detail { get; set; }
        public string SPAofHit_BuntingAbility { get; set; }
    }
}
