//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRockies_one.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PitcherSplit
    {
        public long PlayerId { get; set; }
        public string CareerRHB { get; set; }
        public string CareerLHB { get; set; }
        public int Year { get; set; }
    }
}
