//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRockies_one.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PitcherProfile_PitchCountLastStart
    {
        public long PlayerId { get; set; }
        public Nullable<long> mlbam { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Date { get; set; }
        public string TotalPitches_vsLHH { get; set; }
        public string FB_vsLHH { get; set; }
        public string SL_vsLHH { get; set; }
        public string CB_vsLHH { get; set; }
        public string CH_vsLHH { get; set; }
        public string SPL_vsLHH { get; set; }
        public string TotalPitches_vsRHH { get; set; }
        public string FB_vsRHH { get; set; }
        public string SL_vsRHH { get; set; }
        public string CB_vsRHH { get; set; }
        public string CH_vsRHH { get; set; }
        public string SPL_vsRHH { get; set; }
        public string TotalPitches_Total { get; set; }
        public string FB_Total { get; set; }
        public string SL_Total { get; set; }
        public string CB_Total { get; set; }
        public string CH_Total { get; set; }
        public string SPL_Total { get; set; }
    }
}
