//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRockies_one.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitcher
    {
        public int PlayerID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Dexterity { get; set; }
        public string FastballVelocity { get; set; }
        public string FastballDescription { get; set; }
        public string SinkerVelocity { get; set; }
        public string SinkerDescription { get; set; }
        public string CutterVelocity { get; set; }
        public string CutterDescription { get; set; }
        public string SliderVelocity { get; set; }
        public string SliderDescription { get; set; }
        public string CurveballVelocity { get; set; }
        public string CurveballDescription { get; set; }
        public string ChangeupVelocity { get; set; }
        public string ChangeupDescription { get; set; }
        public string SplitfingerVelocity { get; set; }
        public string SplitfingerDescription { get; set; }
        public string KnuckleballVelocity { get; set; }
        public string KnuckleballDescription { get; set; }
        public string ScrewballVelocity { get; set; }
        public string ScrewballDescription { get; set; }
        public string MOVES { get; set; }
        public string NOTES { get; set; }
        public string STRENGTHS { get; set; }
        public string WEAKNESSES { get; set; }
        public string TENDENCIES { get; set; }
        public string ArmAngle { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
