//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRockies_one.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PitcherProfile_CurrentAndSplits
    {
        public long PlayerId { get; set; }
        public Nullable<long> mlbam { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string G { get; set; }
        public string Record { get; set; }
        public string ERA { get; set; }
        public string IP { get; set; }
        public string H { get; set; }
        public string HR { get; set; }
        public string BB { get; set; }
        public string SO { get; set; }
        public string SBA { get; set; }
        public string PperPA { get; set; }
        public string PperIP { get; set; }
        public string PperGS { get; set; }
        public string GB__Overall { get; set; }
        public string FB__Overall { get; set; }
        public string AVG_vsLHH { get; set; }
        public string H_vsLHH { get; set; }
        public string HR_vsLHH { get; set; }
        public string BB_vsLHH { get; set; }
        public string SO_vsLHH { get; set; }
        public string PperPA_vsLHH { get; set; }
        public string OBP_vsLHH { get; set; }
        public string SLG_vsLHH { get; set; }
        public string GB__vsLHH { get; set; }
        public string FB__vsLHH { get; set; }
        public string AVG_vsRHH { get; set; }
        public string H_vsRHH { get; set; }
        public string HR_vsRHH { get; set; }
        public string BB_vsRHH { get; set; }
        public string SO_vsRHH { get; set; }
        public string PperPA_vsRHH { get; set; }
        public string OBP_vsRHH { get; set; }
        public string SLG_vsRHH { get; set; }
        public string GB__vsRHH { get; set; }
        public string FB__vsRHH { get; set; }
        public string BasesEmpty_AllCounts_Change__Pitches { get; set; }
        public string BasesEmpty_AllCounts_Curve__Pitches { get; set; }
        public string BasesEmpty_AllCounts_Cutter__Pitches { get; set; }
        public string BasesEmpty_AllCounts_FB__4sm___2sm___Pitches { get; set; }
        public string BasesEmpty_AllCounts_Knuckleball__Pitches { get; set; }
        public string BasesEmpty_AllCounts_Slider__Pitches { get; set; }
        public string BasesEmpty_AllCounts_Split_Finger__Pitches { get; set; }
        public string BasesEmpty_FirstPitch_Change__Pitches { get; set; }
        public string BasesEmpty_FirstPitch_Curve__Pitches { get; set; }
        public string BasesEmpty_FirstPitch_Cutter__Pitches { get; set; }
        public string BasesEmpty_FirstPitch_FB__4sm___2sm___Pitches { get; set; }
        public string BasesEmpty_FirstPitch_Knuckleball__Pitches { get; set; }
        public string BasesEmpty_FirstPitch_Slider__Pitches { get; set; }
        public string BasesEmpty_FirstPitch_Split_Finger__Pitches { get; set; }
        public string BasesEmpty_PitcherAhead_Change__Pitches { get; set; }
        public string BasesEmpty_PitcherAhead_Curve__Pitches { get; set; }
        public string BasesEmpty_PitcherAhead_Cutter__Pitches { get; set; }
        public string BasesEmpty_PitcherAhead_FB__4sm___2sm___Pitches { get; set; }
        public string BasesEmpty_PitcherAhead_Knuckleball__Pitches { get; set; }
        public string BasesEmpty_PitcherAhead_Slider__Pitches { get; set; }
        public string BasesEmpty_PitcherAhead_Split_Finger__Pitches { get; set; }
        public string BasesEmpty_PitcherBehind_Change__Pitches { get; set; }
        public string BasesEmpty_PitcherBehind_Curve__Pitches { get; set; }
        public string BasesEmpty_PitcherBehind_Cutter__Pitches { get; set; }
        public string BasesEmpty_PitcherBehind_FB__4sm___2sm___Pitches { get; set; }
        public string BasesEmpty_PitcherBehind_Knuckleball__Pitches { get; set; }
        public string BasesEmpty_PitcherBehind_Slider__Pitches { get; set; }
        public string BasesEmpty_PitcherBehind_Split_Finger__Pitches { get; set; }
        public string BasesEmpty_2Ks__Excl3_2_Change__Pitches { get; set; }
        public string BasesEmpty_2Ks__Excl3_2_Curve__Pitches { get; set; }
        public string BasesEmpty_2Ks__Excl3_2_Cutter__Pitches { get; set; }
        public string BasesEmpty_2Ks__Excl3_2_FB__4sm___2sm___Pitches { get; set; }
        public string BasesEmpty_2Ks__Excl3_2_Knuckleball__Pitches { get; set; }
        public string BasesEmpty_2Ks__Excl3_2_Slider__Pitches { get; set; }
        public string BasesEmpty_2Ks__Excl3_2_Split_Finger__Pitches { get; set; }
        public string RISP_AllCounts_Change__Pitches { get; set; }
        public string RISP_AllCounts_Curve__Pitches { get; set; }
        public string RISP_AllCounts_Cutter__Pitches { get; set; }
        public string RISP_AllCounts_FB__4sm___2sm___Pitches { get; set; }
        public string RISP_AllCounts_Knuckleball__Pitches { get; set; }
        public string RISP_AllCounts_Slider__Pitches { get; set; }
        public string RISP_AllCounts_Split_Finger__Pitches { get; set; }
        public string RISP_FirstPitch_Change__Pitches { get; set; }
        public string RISP_FirstPitch_Curve__Pitches { get; set; }
        public string RISP_FirstPitch_Cutter__Pitches { get; set; }
        public string RISP_FirstPitch_FB__4sm___2sm___Pitches { get; set; }
        public string RISP_FirstPitch_Knuckleball__Pitches { get; set; }
        public string RISP_FirstPitch_Slider__Pitches { get; set; }
        public string RISP_FirstPitch_Split_Finger__Pitches { get; set; }
        public string RISP_PitcherAhead_Change__Pitches { get; set; }
        public string RISP_PitcherAhead_Curve__Pitches { get; set; }
        public string RISP_PitcherAhead_Cutter__Pitches { get; set; }
        public string RISP_PitcherAhead_FB__4sm___2sm___Pitches { get; set; }
        public string RISP_PitcherAhead_Knuckleball__Pitches { get; set; }
        public string RISP_PitcherAhead_Slider__Pitches { get; set; }
        public string RISP_PitcherAhead_Split_Finger__Pitches { get; set; }
        public string RISP_PitcherBehind_Change__Pitches { get; set; }
        public string RISP_PitcherBehind_Curve__Pitches { get; set; }
        public string RISP_PitcherBehind_Cutter__Pitches { get; set; }
        public string RISP_PitcherBehind_FB__4sm___2sm___Pitches { get; set; }
        public string RISP_PitcherBehind_Knuckleball__Pitches { get; set; }
        public string RISP_PitcherBehind_Slider__Pitches { get; set; }
        public string RISP_PitcherBehind_Split_Finger__Pitches { get; set; }
        public string RISP_2Ks__Excl3_2_Change__Pitches { get; set; }
        public string RISP_2Ks__Excl3_2_Curve__Pitches { get; set; }
        public string RISP_2Ks__Excl3_2_Cutter__Pitches { get; set; }
        public string RISP_2Ks__Excl3_2_FB__4sm___2sm___Pitches { get; set; }
        public string RISP_2Ks__Excl3_2_Knuckleball__Pitches { get; set; }
        public string RISP_2Ks__Excl3_2_Slider__Pitches { get; set; }
        public string RISP_2Ks__Excl3_2_Split_Finger__Pitches { get; set; }
        public string C3_2_Change__Pitches { get; set; }
        public string C3_2_Curve__Pitches { get; set; }
        public string C3_2_Cutter__Pitches { get; set; }
        public string C3_2_FB__4sm___2sm___Pitches { get; set; }
        public string C3_2_Knuckleball__Pitches { get; set; }
        public string C3_2_Slider__Pitches { get; set; }
        public string C3_2_Split_Finger__Pitches { get; set; }
        public string StrikeZone__Change { get; set; }
        public string Chase__Change { get; set; }
        public string StrikeZone__Curve { get; set; }
        public string Chase__Curve { get; set; }
        public string StrikeZone__Cutter { get; set; }
        public string Chase__Cutter { get; set; }
        public string StrikeZone__FB__4sm___2sm_ { get; set; }
        public string Chase__FB__4sm___2sm_ { get; set; }
        public string StrikeZone__Knuckleball { get; set; }
        public string Chase__Knuckleball { get; set; }
        public string StrikeZone__Slider { get; set; }
        public string Chase__Slider { get; set; }
        public string StrikeZone__Split_Finger { get; set; }
        public string Chase__Split_Finger { get; set; }
    }
}
