//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRockies_one.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_table
    {
        public int ID { get; set; }
        public Nullable<double> Player_ID { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string MI { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<double> Team_ID { get; set; }
        public string Bats { get; set; }
        public string Throws { get; set; }
        public string Hitter_or_Pitcher { get; set; }
        public Nullable<double> Uniform__ { get; set; }
        public string Position { get; set; }
        public bool select_ { get; set; }
        public bool Active_ { get; set; }
        public string Stance { get; set; }
        public string C5th_Pitch { get; set; }
        public string Time_to_Plate { get; set; }
        public string Secondary { get; set; }
        public string txn { get; set; }
        public Nullable<double> MLBID { get; set; }
        public Nullable<int> espnID { get; set; }
        public Nullable<int> TwoKID { get; set; }
        public Nullable<int> YahooID { get; set; }
        public Nullable<int> mlbam { get; set; }
        public string Status { get; set; }
        public string NickNotes { get; set; }
        public Nullable<bool> C40Man { get; set; }
        public string BBRefID { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public Nullable<int> MLB_TeamID { get; set; }
    }
}
