//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRockies_one.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team_table
    {
        public int Team_ID { get; set; }
        public string City_or_State { get; set; }
        public string Nickname { get; set; }
        public string League { get; set; }
        public string Division { get; set; }
        public string Shortname { get; set; }
        public string espnShortname { get; set; }
        public string Stadium { get; set; }
        public bool CustomDims { get; set; }
        public string LF { get; set; }
        public string MidLF { get; set; }
        public string LCF { get; set; }
        public string MidLCF { get; set; }
        public string CF { get; set; }
        public string MidRCF { get; set; }
        public string RCF { get; set; }
        public string MidRF { get; set; }
        public string RF { get; set; }
        public bool Last_Referenced { get; set; }
        public string MLBID { get; set; }
        public string TwoKTeamID { get; set; }
        public bool Active_ { get; set; }
        public string YahooTeamID { get; set; }
        public string MLBcity { get; set; }
        public string C2k_Mnemonic { get; set; }
        public Nullable<double> MLB_AffiliateID { get; set; }
        public string BITteamName { get; set; }
        public string mlb_shortName { get; set; }
        public string mlb_sportcode { get; set; }
    }
}
