//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRockies_one.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEntered2
    {
        public long PlayerID { get; set; }
        public string FB2SMVelocity { get; set; }
        public string FB2SMDescription { get; set; }
        public string FB4SMVelocity { get; set; }
        public string FB4SMDescription { get; set; }
        public string FB2SMCommand { get; set; }
        public string FB4SMCommand { get; set; }
        public string CutterCommand { get; set; }
        public string SliderCommand { get; set; }
        public string CurveballCommand { get; set; }
        public string ChangeupCommand { get; set; }
        public string SplitfingerCommand { get; set; }
        public string KnuckleballCommand { get; set; }
    }
}
