//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRockies_one.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEntered
    {
        public long PlayerID { get; set; }
        public string ArmSlot { get; set; }
        public string Control { get; set; }
        public string Command { get; set; }
        public string Approach { get; set; }
        public string Out_Pitch { get; set; }
        public string PickoffMove_1B { get; set; }
        public string PickoffMove_2B { get; set; }
        public string ReleaseTimes_1B { get; set; }
        public string ReleaseTimes_2B { get; set; }
        public string ReleaseTimes_SS { get; set; }
        public string SlideStepTime_1B { get; set; }
        public string LooksWRunner_2B { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
